Swap backend
go-bazzinga/hot-or-not-backend-canister pull request #448
Opened 2024-11-06 08:32 UTC by joel-medicala-yral

#447 
#### To check the status of the deployment

- check if the platform orchestrator performed the step to upgrade subnet canister with appropriate version: [Platform Orchestrator function](https://dashboard.internetcomputer.org/canister/74zq4-iqaaa-aaaam-ab53a-cai#get_subnet_last_upgrade_status)
- check the status of upgrade for individual canisters in subnet orchestrators and verify the version. Example for one of the subnet orchesrator: [Subnet Orchestrator function](https://dashboard.internetcomputer.org/canister/rimrc-piaaa-aaaao-aaljq-cai#get_index_details_last_upgrade_status)

To test the platform orchestrator, you can use the following command:

`dfx canister call --query 74zq4-iqaaa-aaaam-ab53a-cai get_subnet_last_upgrade_status --network=ic`
 the canister id (74zq4-iqaaa-aaaam-ab53a-cai) is taken from the canister_ids.json file

2024-11-06 10:16 UTC, ravi-sawlani-yral commented
Could we add details into the issue what is this is trying to fix?

2024-11-06 10:28 UTC, joel-medicala-yral commented
> Could we add details into the issue what is this trying to fix?

Umm this is the swap backend implementation im just writing the tests and its trail and error because i cant locally run the tests... I'll add the meramaids for better understanding

2025-02-06 07:55 UTC, ravi-sawlani-yral commented on src/canister/individual_user_template/src/api/cdao/swap.rs
> +        return Err(SwapError::Unauthenticated);
use guard instead #[update(guard = "is_caller_profile_owner")]. If there are no guards lets add that into individual canister `utils/guard.rs`. That way when a change comes up we only need to change once.

2025-02-06 08:17 UTC, joel-medicala-yral commented on src/canister/individual_user_template/src/api/cdao/swap.rs
> +        return Err(SwapError::Unauthenticated);
ok will add that

2025-02-06 08:26 UTC, joel-medicala-yral commented on src/canister/individual_user_template/src/api/cdao/swap.rs
> +        return Err(SwapError::Unauthenticated);
doesnt seem like there's any actually

2025-02-06 08:27 UTC, joel-medicala-yral commented on src/canister/individual_user_template/src/api/cdao/swap.rs
> +        return Err(SwapError::Unauthenticated);
yeh wala nhi chalega kya? 

```
pub fn is_caller_controller() -> Result<(), String> {
    if !is_controller(&caller()) {
        return Err("Unauthorize".into());
    }
    Ok(())
}
```

2025-02-06 08:35 UTC, ravi-sawlani-yral commented on src/canister/individual_user_template/src/api/cdao/swap.rs
> +        return Err(SwapError::Unauthenticated);
Nope we need to add another function that would actually utilise canister data from idnividual canister.

2025-02-06 08:39 UTC, joel-medicala-yral commented on src/canister/individual_user_template/src/api/cdao/swap.rs
> +        return Err(SwapError::Unauthenticated);
ah ok alright ill add that

2025-02-06 08:43 UTC, ravi-sawlani-yral requested changes

2025-02-06 08:43 UTC, ravi-sawlani-yral commented on src/canister/individual_user_template/src/api/profile/get_profile_details_v2.rs
> +pub fn get_profile_details_v2() -> UserProfileDetailsForFrontendV2 {
why is this necessary?

2025-02-06 08:43 UTC, ravi-sawlani-yral commented on src/canister/individual_user_template/Cargo.toml
> +bigdecimal = "0.4.6"
is this used anywhere?

2025-02-06 08:43 UTC, ravi-sawlani-yral commented on src/canister/individual_user_template/src/api/cdao/swap.rs
> +    transfer_res.0.map_err(SwapError::TransferFromError)?;
if this transfer fails shouldn't we reverse the previous transaction?

2025-02-06 08:43 UTC, ravi-sawlani-yral commented on src/lib/integration_tests/tests/creator_dao/main.rs
> +    let bob_initial_cycle_balance = pocket_ic.cycle_balance(bob_canister_id);
We could add this as a separate test.

2025-02-06 10:06 UTC, joel-medicala-yral commented on src/canister/individual_user_template/src/api/cdao/swap.rs
> +    transfer_res.0.map_err(SwapError::TransferFromError)?;
This will be done in leptos server function only there we'll be checking the balance of both parties and then only proceeding thats the only point of failure na?

Because problem here is that once transfered we cant reverse the full amount due to fees and stuff

2025-02-06 10:06 UTC, joel-medicala-yral commented on src/lib/integration_tests/tests/creator_dao/main.rs
> +    let bob_initial_cycle_balance = pocket_ic.cycle_balance(bob_canister_id);
yeah will do that

2025-02-06 10:48 UTC, ravi-sawlani-yral commented on src/canister/individual_user_template/src/api/cdao/swap.rs
> +    transfer_res.0.map_err(SwapError::TransferFromError)?;
Alright. But do add a check on server functions to check if both canisters are reachable. There is a common problem of canisters running out of cycles. If both canisters are active and responding then we can move ahead with transaction.

2025-02-07 09:31 UTC, joel-medicala-yral commented on src/canister/individual_user_template/src/api/profile/get_profile_details_v2.rs
> +pub fn get_profile_details_v2() -> UserProfileDetailsForFrontendV2 {
I think to do the guard i need it to be public na?

2025-03-17 12:50 UTC, ravi-sawlani-yral commented on src/canister/individual_user_template/src/api/profile/get_profile_details_v2.rs
> +pub fn get_profile_details_v2() -> UserProfileDetailsForFrontendV2 {
There is no guard as such in this method.

2025-03-17 12:54 UTC, ravi-sawlani-yral commented on src/lib/shared_utils/src/canister_specific/individual_user_template/types/cdao/mod.rs
> +    pub last_swapped_price: Option<f64>
Isn't it a breaking change as frontend might be already consuming `DeployedCdaoCanisters` and we are changing the struct?

2025-03-17 15:29 UTC, ravi-sawlani-yral commented on src/lib/shared_utils/src/canister_specific/individual_user_template/types/cdao/mod.rs
> +    pub last_swapped_price: Option<f64>
That would still break the ui for seconds. The better idea is to use separate Struct for frontend and storage and not make any changes in the struct that used in apis

2025-03-17 15:29 UTC, ravi-sawlani-yral commented
@joel-medicala-yral Could we also resolve the merge conflicts here.

2025-07-31 06:43 UTC, closed without merging